language: java
jdk:
- openjdk11
notifications:
  slack:
    secure: bDWs9L5Au5Evv00GJXM4KCxRRonmqB+fxDHApbwftRvNdJr1q6Us6GecR63sL+NKkHlLnAPfLvTowvs1LTDKiFYY0UTbI+vqYdqGQ0Gnvb7kDoJRPzEVCVdhNu1DVgRHlDL8a/C9dTLppb+7uQ8QzGbdKxurxiTdYdx8TAJt0CCpmVjo5ETYBHrtdMRbPvLLoUnvun53DeFvuoKCAedbka5P8919r3DqloPhMZXc67ev+T7zO1ivYtaRZmSi5vlWtzIRrvnkaABKBKLyuAYaG3VFe2tjJNYGbUUICMNbCttGc3Eo84zoxsfUbBB1egAbPAvXjUQ2PTC5Ttn8ahxCujZPk16NXWRtDBVMmEqxREEu03HTT4JhFvucKp+nO7Y7/nFvGg317ArCnOhHraEi7li4e6VPhdZhvAUmMWJWaw16sCeceN+EUz9zCFDI0sU8lPvaYhwDXPAoBNCXQ/uNeNSznmjAWJ93k9c4fJenzAp2DarclKUjN4gSFnQqbaGIWl905wSSg3SZrbSc1Tp4CC5lHWxoq60J1i0+Ujf4TTxJQqmyHVD04Liah9Zcaf8tcwJBwNXlIZHjsJJdZwACEJhNkbFDzhujGEEJHz/BDGNLp4oSMNeOtgxRyXmvEgx41vyWL9e5Tj6GTYns+pFIxqS28GmGeTTZMEG1VlC9jIY=
    if: branch = master
