language: java
jdk:
- openjdk11
script:
  - jdk_switcher use openjdk11
  # Install Java 17 to use instead of Java 11
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
notifications:
  slack:
    if: branch = master
    rooms:
      - monsieurmahjo-7ov7889:LzYyuiGljzdRuf4Mvzp8McqS#commonjong
