language: java
jdk:
- openjdk11
notifications:
  slack:
    secure: TCcJ5GSDnBPUWSMKVR5JN5alXGydvhbAXcYYVoonlgoFphv7wiqrzEJO/Y30VWJAYvNPvPF2ufPTXhNBkkU+QJgoE4unpw3LzZ4fIse1r2GKaY7q/BhS2YK638PnTmCc2BHAtg1bxbI+ZXASZ7YP5c8MhuZ5bx8dGJOGuhzAxpMoZnve9w9JXJNCBrmuk1IyIDrTHm0p/2SPXLuItk3QnReMxEy+2+mLgKN52FgA9lT8PO6YT4EpXqb9ZHCgDMKFATw9SNA/tmk5ZpZVlXwCIlToSsorN5egEQceDiNMBpSJftlDsGZAY+4FgPSNpay+9gyb0pgiCMUWLmci4PRcBMM5Yr8EOhmimMBHfloAIcXwdVuDr7TFJhOtlGiLoor+m6FOIFJgq1kFBwVPJ6+tHm/jEkT6qGYmtlNliKqg6RhR4WcNSldHcwZJwSC6oTXw5loBE31LFewLzXMm8r8jA7C5kyTk/etUNVNB4+D5FwPD09Va4SxuYEnxxo+CmHSpEpU9qdAJN5B5KVfccvXm8zPFBtYESQOyJmucsN4iZm7exlXzB/Uw3rft5MsD0oyHkYNw/SNkAGzJ1iYkdYEJ6AWmYUyd1En7bul5jD1MFLWB4gPNMOTczKa0BhU/9OlmlLfGVhZPtDPLNYrer4xdE8ibLKhlMlfPx8NUzimkqaQ=
