language: java
jdk:
- openjdk11
notifications:
  slack:
    secure: JYjVSbcz0UvLpcJzEFMEHuUmvuU1f5KRSIEBRSTeFnUAgtHOOglyiOs8HeCxd5hnWlgSxA/jdaKXB0Lg9+cW06NigMrZgPKCSOwf0OhS2+A5oVAV8WvBoa9EKWZsQT2fnUd6Z1uH5HTut8IbtGgsML+ZwG/nzi+7pfCUg/ffD5uZI7y+gpHhu/bHE25H1/bH6jNQb6sTvSO8qPbe3FLCYk4yiSTPxUTtsYYYni2cCemrzR2NVX4JIg96echyXZ8SmQnh3ItVV4t9Fr9j9sT7BmND0iouJzUnabnE6H2ywq+woKHIW3HLq5ApNx6TW9JM5E2Z4lTAozlqiXNJWZghEwwJ0F4Ubs32hjeIIqYI8LRObtIgJnw1i5y1twihkgfmg4wW3O/3XE5ndLlRKTt4dhd+RE5YLLPa0X1BJkgq3fDnuiFxaxuzZCBIOasJ0L6H0FJfjSQitotVpJcHcIkopAfbJOxO17af6HWb662oJduHBY/zDT4eqrNpKIdA09SbUH0mDJ9ApB+gwg0jaM5vNGN+zg8oYSJhYNcjqVgTZrLtda7SDkzjQyTDi0Nol3+XMRabFXl+4b8/0rnfX9lWOIH7G9f7eOcrDOy3zkLMfj1nBEr5Q6IcnTIyFxU66SO/vBjmzLncF2OeLRajh6mg4K+gXExCigrNzLD+mc3gnqQ=
    if: branch = master
